name: GitHub Action with AWS CLI command exec
on:
  push:
    branches:
      - main
env:
  AWS_REGION: "ap-south-1"
  S3_BUCKET: "gitops-demo-bucket-tf"
  IAM_ROLE: "arn:aws:iam::282526987315:role/oidc-github-aws-connection"
  LIST_USER: "aws iam list-users"
  LIST_ROLES: "aws iam list-roles"
  CALLER_IDENTITY: "aws sts get-caller-identity"
permissions:
  id-token: write
  contents: read
jobs:
  gitaction:
    name: CICD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3 
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: Github
          aws-region: ${{ env.AWS_REGION }}
      - name: Executing AWS CLI command sets
        run: |
          echo "List out available S3 buckets in region ${{ env.AWS_REGION }}"
          aws s3 ls --region ${{ env.AWS_REGION }}
          echo "List out files in ${{ env.S3_BUCKET }}"
          aws s3 ls ${{ env.S3_BUCKET }}

      - name: Executing AWS CLI commands
        run: |
          echo "Running AWS CLI commands.."
          ${{ env.LIST_USER }}
          ${{ env.LIST_ROLE }}
          ${{ env.CALLER_IDENTITY }}
        




          
