name: AWS OIDC Authentication
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials using OIDC
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::282526987315:role/openid-connect-github
          aws-region: ap-south-1
          audience: sts.amazonaws.com
          role-session-name: GitHubActionsSession

      - name: List S3 buckets
        run: |
          echo "Listing out S3 buckets available in the Mumbai region in AWS account"
          aws s3 ls --region ap-south-1
