name: "Testing GitHub Workflow Variables"
# on:
#   push:
#     branches:
#       - main
on:
  workflow_disptach
env:
  mycorp: My corp
  corp: try-devops.xyz
  primary_cloud: aws-cloud
  secondary_cloud: azure-cloud
  additional_cloud: VMware-cloud
jobs:
  variable_testing:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Hello, you are working at: ${{ env.corp }}"
        run: |
          echo "${{ env.Greeting }} ${{ env.mycorp }} is primarily using cloud as: ${{ env.primary_cloud }}"
          echo "${{ env.Greeting }} ${{ env.mycorp }} is secondarily using cloud as: ${{ env.secondary_cloud }}"
          echo "${{ env.Greeting }} ${{ env.mycorp }} is additionally using cloud as: ${{ env.additional_cloud }}"
